services:
  - type: web
    name: seccional-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    # Opción A (más simple) si en backend/app.py exportás "app = create_app()":
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    # Opción B si NO exportás "app" y querés llamar a la factory:
    # startCommand: gunicorn app:create_app --bind 0.0.0.0:$PORT

    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: CORS_ORIGINS
        value: https://seccional-uf.vercel.app,https://*.vercel.app,http://localhost:5173
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
